apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: school-app
  namespace: argocd
spec:
  project: default

  source:
    # GitHub Pages URL (Helm repository)
    repoURL: https://omkartakalkar19.github.io/School-Docker
    chart: school-app
    # Deploy latest released chart version
    targetRevision: "*"  # it will deploy the latest version of the chart available in the helm repository
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: omkar-ns 

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
